import Head from 'next/head'
import Image from 'next/legacy/image'

import { Figtree, Inter } from '@next/font/google'
import { useState, useEffect } from 'react'
import { RiMoonFill, RiSunFill } from 'react-icons/ri'
import { AiFillLinkedin, AiFillTwitterCircle, AiFillFacebook, AiFillGithub } from 'react-icons/ai'
import { FiGithub ,FiExternalLink} from 'react-icons/fi'
import { GrLinkedinOption } from 'react-icons/gr'
import { SiLeetcode, SiGmail, SiCodechef } from 'react-icons/si'
import styles from '../styles/Home.module.css'
import img from '../public/seimg.jpg';
import { RxHamburgerMenu } from 'react-icons/rx'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [dark, setdark] = useState(true);
  const [visible, setvisible] = useState(false);
  //  useEffect(()=>{
  //   let initialScroll=0
  //   window.addEventListener('scroll',()=>{
  //   let currScroll =  window.scrollY; 
  //   if(currScroll-initialScroll<0 ){
  //       setvisible(false);
  //   }
  //   else{
  //     setvisible(false);
  //   }
  //   initialScroll=currScroll;
  //   })
  //  },[])

  return (

    <div className={dark ? "dark" : " "}>
      <Head>
       
        <title>Raghav Kumar Jha</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-10 bg-white md:px-20 lg:px-60 dark:bg-darkbg dark:text-white italic' >
        <section >
        {/* NavBar */}
          <nav className='py-10 mb-10 flex   justify-between font-lobster text-xl md:text-3xl ' >
            <h1 className='  font-lobster dark:text-hovcol text-gray-700 mx-2 my-2 '>PORTFOLIO</h1>
            <ul className='flex items-center'>
              <div className='md:flex hidden'>

                <li className='text-xl dark:hover:text-hovcol mx-2 dark:text-blue-200 text-blue-800 ' ><a href='#about' className='active:text-hovcol'>About</a></li>
                <li className='text-xl dark:hover:text-hovcol mx-2 dark:text-blue-200 text-blue-800'><a href='#project'>Project</a></li>
                <li className='text-xl dark:hover:text-hovcol mx-2 dark:text-blue-200 text-blue-800'><a href='#skills'>Skill</a></li>
                <li className='text-xl dark:hover:text-hovcol mx-2 dark:text-blue-200 text-blue-800'><a href='#achievment'>Achievment</a></li>
                <li className='text-xl dark:hover:text-hovcol mx-2 dark:text-blue-200 text-blue-800'><a href='#contact'>Contact</a></li>
              </div>
              <li className='py-2 px-4 bg-blue-400 hover:bg-blue-500 rounded-md  text-black ml-5 font-lobster dark:bg-slate-800  dark:hover:bg-slate-700 dark:text-hovcol '><a href='https://drive.google.com/file/d/1BhoTwewBprnSG5Q9xTRUW_9lgyz3aG82/view?usp=share_link' target="_blank" rel='noopener noreferrer'>Resume</a></li>
              <li className=' cursor-pointer ml-3 '><RiMoonFill onClick={() => {
                setdark(!dark)
              }} className="  dark:hidden " /></li>
              <li className=' cursor-pointer '><RiSunFill onClick={() => {
                setdark(!dark)
              }} className="hidden dark:text-yellow-400 dark:block   text-xl md:text-4xl " /></li>


            </ul>
          </nav>
          {/* Small introduction Section  */}
          <div className='text-center text-gray-700 p-10 font-lobster dark:text-white'>
            {/* <p className='text-hovcol text-2xl '>Hi , my name is  </p> */}
            <h1 className=' text-4xl font-lobster text-blue-800  md:text-7xl dark:text-blue-200  '>Raghav Kumar Jha</h1>
            <h2 className='text-2xl font-lobster pb-3 md:text-4xl text-blue-800 dark:text-blue-200'>Software Developer</h2>
            <p className=' text-lg py-3 leading-7 max-w-lg mx-auto md:text-2xl'>Highly motivated  always eager to learn new skills passionate about web-development  and problem-solving wanted to contribute in software development field</p>
          </div>
          <div className='flex flex-wrap justify-center text-3xl text-gray-700 gap-16 pb-20 md:text-5xl  dark:text-slate-300'>
            <a href='https://www.linkedin.com/in/jharaghav/' target="_blank"  rel='noopener noreferrer'>
              <AiFillLinkedin className='hover:text-blue-800 hover:dark:text-hovcol hover:-translate-y-1' />
            </a>
            <a href='https://github.com/jharaghav32' target="_blank" rel='noopener noreferrer'>
              <AiFillGithub className='hover:text-black hover:dark:text-hovcol hover:-translate-y-1' />
            </a>
            <a href='https://leetcode.com/raghav32/' target="_blank" rel='noopener noreferrer'>

              <SiLeetcode className='hover:text-orange-400 hover:dark:text-hovcol hover:-translate-y-1' />
            </a>
            <a href='https://www.codechef.com/users/jharaghav_3209' target="_blank" rel='noopener noreferrer'>

              <SiCodechef className='hover:text-orange-700 hover:dark:text-hovcol hover:-translate-y-1 ' />
            </a>
          </div>
        </section>
        {/* About section */}
        <section >
          <div className='text-center text-gray-700 font-lobster py-10 dark:text-white '>
            <fieldset className="border-t border-slate-500 dark:border-hovcol">
              <legend className="mx-auto px-4 text-black text-2xl italic"> <h3 id='about' className=' text-4xl  md:text-6xl dark:text-blue-200 text-blue-800'>About Me<br /></h3></legend>
            </fieldset>
            <div className='pt-10'>
            <Image src="/img.jpg" width={140} height={140} className='rounded-full  '/>
            </div>


            <p className='text-lg  py-3 leading-8 md:text-2xl max-w-lg mx-auto'>Hi, I am Raghav , a 2024 undergraduate currently pursuing Bachelor of Technology from Maharja Agrasen Institute of Technology specialised in Information Technology Department.  </p>

            <p className='text-lg py-3 leading-8 max-w-lg mx-auto md:text-2xl'>I have a deep interest in web-development and enjoyed learning new stuff . I   have made several projects using MERN stack.Apart from that I enjoyed solving problems and have solved more than 1000+ problem on various coding platforms. I am a 3 star coder at codechef and have   max-rating of 1600+ on leetcode.</p>
          </div>
          {/* Projects Section  */}
          <fieldset id='project' className="mt-10 py-2 border-t border-slate-500 dark:border-hovcol font-lobster ">
            <legend className="mx-auto px-4 text-black text-2xl italic"> <h3 id='about' className=' text-4xl md:text-6xl dark:text-blue-200 text-blue-800 '>My Projects<br /></h3></legend>
          </fieldset>
          {/* Project---1 */}
          <div className='md:flex md:flex-wrap  gap-10 justify-center'>
            {/* <h1 className=' text-4xl py-2 md:text-5xl dark:text-blue-200 text-center'>My Projects</h1> */}
            <div className=' text-center p-10 text-gray-700 font-lobster shadow-lg rounded-xl my-8 md:w-5/12 dark:text-white dark:bg-dcardbg hover:-translate-y-2'>
              <div className='flex justify-center m-1'>
                <Image src="/has.jpg" alt='' width={100} height={100} />
              </div>
              <h3 className='text-2xl md:text-3xl'><span className='dark:text-blue-200 text-blue-800'>Memories</span><a href='https://github.com/jharaghav32/CloudMemories' target="_blank" rel='noopener noreferrer'>
                <FiGithub className=' inline cursor-pointer hover:text-blue-800 dark:hover:text-hovcol text-xl md:text-2xl ml-3' />
              </a>
              </h3>
              <p className='text-lg py-1 md:text-xl'>Implemented a full stack project  where user can store their memories. They can create , able to
                update and delete it and no other users can access it. User's  authentication is done using
                bcrypt and jwt</p>
              <h4 className='text-xl md:text-2xl'>ReactJs NodeJs MongoDB</h4>

            </div>
            {/* Project---2 */}
            <div className='text-center p-10 text-gray-700 font-lobster shadow-lg rounded-xl my-8 md:w-5/12 dark:text-white dark:bg-dcardbg hover:-translate-y-2'>
              <div className='flex justify-center m-1'>
                <Image src="/has.jpg" alt='' width={100} height={100} className=''  />
              </div>
              <h3 className='text-2xl md:text-3xl'><span className='dark:text-blue-200 text-blue-800'>CoinWorld</span>
                <a href='https://coinworld25.netlify.app/' target="_blank" rel='noopener noreferrer'>
                  <FiExternalLink className=' inline  hover:text-blue-800 cursor-pointer dark:hover:text-hovcol text-xl md:text-2xl ml-3 mb-2' /></a></h3>
              <p className='text-lg py-1 md:text-xl'>Implemented a coinworld which gives the data of all cryptocurrencies its prices,its market valuation and daily changes
                it gives the trending graph of various currencies and various news related to crypto</p>
              <h4 className='text-xl md:text-2xl'>ReactJs RapidApi AntDesign </h4>

            </div>
            {/* Project---4 */}
            <div className='text-center p-10 text-gray-700 font-lobster shadow-lg rounded-xl my-8 md:w-5/12 dark:text-white dark:bg-dcardbg hover:-translate-y-2'>
              <div className='flex justify-center m-1'>
                <Image src="/has.jpg" alt='' width={100} height={100} />
              </div>
              <h3 className='text-2xl md:text-3xl'><span className='dark:text-blue-200 text-blue-800'>YourNews</span>
                <a href='https://github.com/jharaghav32/YourNews' target="_blank" rel='noopener noreferrer'>
                  <FiGithub className=' inline cursor-pointer hover:text-blue-800 dark:hover:text-hovcol text-xl md:text-2xl ml-3' /></a></h3>
              <p className='text-lg py-1 md:text-xl'>Implemented a news app which provides us the news of various categories along with its published
              date . User's can get detailed views . Used RapidApI for fetching News data</p>
              <h4 className='text-xl md:text-2xl'>ReactJs RapidApi</h4>

            </div>
            {/* Project---3 */}
            <div className='text-center p-10 text-gray-700 font-lobster shadow-lg rounded-xl my-8 md:w-5/12 dark:text-white dark:bg-dcardbg hover:-translate-y-2'>
              <div className='flex justify-center m-1'>
                <Image src="/has.jpg" alt='' width={100} height={100} />
              </div>
              <h3 className='text-2xl md:text-3xl'><span className='dark:text-blue-200 text-blue-800'>Loop</span>
                <a href='https://github.com/jharaghav32/MAIT_SIH' target="_blank" rel='noopener noreferrer'>
                  <FiGithub className=' inline cursor-pointer hover:text-blue-800 dark:hover:text-hovcol text-xl md:text-2xl ml-3' /></a></h3>
              <p className='text-lg py-1 md:text-xl'>It provides   Real time tracking of students learnings outcomes and their academic progress  , track record of student&apos;s performance in both academic and cocurricular activities
                schools.</p>
              <h4 className='text-xl md:text-2xl'>HTML CSS Bootstrap Javascript</h4>

            </div>
              {/* Project---4 */}
              <div className='text-center p-10 text-gray-700 font-lobster shadow-lg rounded-xl my-8 md:w-5/12 dark:text-white dark:bg-dcardbg hover:-translate-y-2'>
              <div className='flex justify-center m-1'>
                <Image src="/has.jpg" alt='' width={100} height={100} />
              </div>
              <h3 className='text-2xl md:text-3xl'><span className='dark:text-blue-200 text-blue-800'>MyVideo App</span>
                <a href='https://github.com/jharaghav32/MyVideoApp' target="_blank" rel='noopener noreferrer'>
                  <FiGithub className=' inline cursor-pointer hover:text-blue-800 dark:hover:text-hovcol text-xl md:text-2xl ml-3' /></a></h3>
              <p className='text-lg py-1 md:text-xl'>
              Implemeted a Video Application (like Youtube Clone) App . 
              Users can see various videos of various categories , able to see Number of views, channel of Uploaders,
              Comments on Video and many more features.
               </p>
              <h4 className='text-xl md:text-2xl'>ReactJs,RapidApi,Material@UI</h4>

            </div>
          </div>
        </section>
        <section id='skills'>
          <div className='text-center text-gray-700 font-lobster py-10 dark:text-white '>
            <fieldset className="border-t border-slate-500 dark:border-hovcol">
              <legend className="mx-auto px-4 text-black text-2xl italic"> <h3 id='about' className=' text-4xl  md:text-6xl dark:text-blue-200 text-blue-800'>Skills<br /></h3></legend>
            </fieldset>
            <div className='md:flex flex-wrap justify-center gap-10'>
              <div className=' p-10 text-gray-700 font-lobster shadow-lg rounded-xl my-8 md:w-5/12 dark:text-white dark:bg-dcardbg hover:-translate-y-2'>
                <h1 className='text-3xl md:text-5xl dark:text-blue-200 text-blue-800 '>Languages</h1>
                <ul className='mt-10'>


                  <li className='p-3'>
                    <h1 className=' text-start'>C</h1>
                    <span className='block h-2 bg-gray-600 w-full'><span className='bg-blue-800 block h-2 w-[90%]  dark:bg-hovcol'></span></span>
                  </li>  <li className='p-3'>
                    <h1 className=' text-start'>C++</h1>
                    <span className='block h-2 bg-gray-600 w-full'><span className='bg-blue-800 block h-2 w-[91%]  dark:bg-hovcol'></span></span>
                  </li>
                  <li className='p-3'>
                    <h1 className=' text-start'>JAVASCRIPT</h1>
                    <span className='block h-2 bg-gray-600 w-full'><span className='bg-blue-800 block h-2 w-[75%]  dark:bg-hovcol'></span></span>
                  </li>
                </ul>
              </div>
              <div className=' p-10 text-gray-700 font-lobster shadow-lg rounded-xl my-8 md:w-5/12 dark:text-white dark:bg-dcardbg hover:-translate-y-2'>
                <h1 className='text-3xl md:text-5xl dark:text-blue-200 text-blue-800'>Web-Frameworks</h1>
                <ul>
                  <li className='p-3'>
                    <h1 className=' text-start'>HTML</h1>
                    <span className='block h-2 bg-gray-600 w-full'><span className='bg-blue-800 block h-2 w-[80%]  dark:bg-hovcol'></span></span>
                  </li>
                  <li className='p-3'>
                    <h1 className=' text-start'>CSS</h1>
                    <span className='block h-2 bg-gray-600 w-full'><span className='bg-blue-800 block h-2 w-[81%]  dark:bg-hovcol'></span></span>
                  </li>
                  <li className='p-3'>
                    <h1 className=' text-start'>NODEJS</h1>
                    <span className='block h-2 bg-gray-600 w-full'><span className='bg-blue-800 block h-2 w-[65%]  dark:bg-hovcol'></span></span>
                  </li>  <li className='p-3'>
                    <h1 className=' text-start'>REACTJS</h1>
                    <span className='block h-2 bg-gray-600 w-full'><span className='bg-blue-800 block h-2 w-[70%]  dark:bg-hovcol'></span></span>
                  </li>
                  <li className='p-3'>
                    <h1 className=' text-start'>MONGODB</h1>
                    <span className='block h-2 bg-gray-600 w-full'><span className='bg-blue-800 block h-2 w-[65%]  dark:bg-hovcol'></span></span>
                  </li>
                </ul>
              </div>
              <div className=' p-10 text-gray-700 font-lobster shadow-lg rounded-xl my-8 md:w-5/12 dark:text-white dark:bg-dcardbg hover:-translate-y-2'>
                <h1 className='text-3xl md:text-5xl dark:text-blue-200 text-blue-800 '>Tools</h1>
                <ul className='mt-3'>


                  <li className='p-3'>
                    <h1 className=' text-start'>GIT</h1>
                    <span className='block h-2 bg-gray-600 w-full'><span className='bg-blue-800 block h-2 w-[70%]  dark:bg-hovcol'></span></span>
                  </li>
                  <li className='p-3'>
                    <h1 className=' text-start'>GITHUB</h1>
                    <span className='block h-2 bg-gray-600 w-full'><span className='bg-blue-800 block h-2 w-[75%]  dark:bg-hovcol'></span></span>
                  </li>
                </ul>
              </div>
              <div className=' p-10 text-gray-700 font-lobster shadow-lg rounded-xl my-8 md:w-5/12 dark:text-white dark:bg-dcardbg hover:-translate-y-2'>
                <h1 className='text-3xl md:text-5xl dark:text-blue-200 text-blue-800 '>Soft-Skills</h1>
                <ul>
                  <li className='p-3'>
                    <h1 className=' text-start'>PROBLEM-SOLVING</h1>
                    <span className='block h-2 bg-gray-600 w-full'><span className='bg-blue-800 block h-2 w-[75%]  dark:bg-hovcol'></span></span>
                  </li>
                  <li className='p-3'>
                    <h1 className=' text-start'>TEAM-WORK</h1>
                    <span className='block h-2 bg-gray-600 w-full'><span className='bg-blue-800 block h-2 w-[70%]  dark:bg-hovcol'></span></span>
                  </li>
                  <li className='p-3'>
                    <h1 className=' text-start'>TIME-MANAGEMENT</h1>
                    <span className='block h-2 bg-gray-600 w-full'><span className='bg-blue-800 block h-2 w-[70%]  dark:bg-hovcol'></span></span>
                  </li>

                </ul>
              </div>
            </div>

            {/* <p className='text-lg py-3 leading-8 md:text-xl max-w-lg mx-auto'>Lorem ipsum dolor sit amet consectetur <span className='text-red-500'>highlighted</span>   adipisicing elit. Rerum, modi voluptate nihil porro esse libero qui, deserunt consequatur non tempora eveniet fuga molestias fugiat beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, distinctio? Sequi, illum dolorum culpa aspernatur deleniti quidem dignissimos impedit ut tempora! Cum voluptatibus corporis inventore!</p>

           <p className='text-lg py-3 leading-8 max-w-lg mx-auto'>Lorem ipsum dolor sit amet consectetur <span className='text-red-500'>highlighted</span>   adipisicing elit. Rerum, modi voluptate nihil porro esse libero qui, deserunt consequatur non tempora eveniet fuga molestias fugiat beatae!</p>  */}
          </div>
        </section>
        <section id='achievment'>
          <div className='text-center text-gray-700 font-lobster py-10 dark:text-white  '>
            <fieldset className="border-t border-slate-500 dark:border-hovcol">
              <legend className="mx-auto px-4 text-black text-2xl italic"> <h3 id='about' className=' text-4xl  md:text-6xl dark:text-blue-200 text-blue-800'>Achievments</h3></legend>
            </fieldset>
            <div className='py-10'>
              <p className='text-lg py-3 leading-8 md:text-2xl max-w-1/2 mx-auto'>Secured <span className='dark:text-hovcol text-blue-800'>top 30</span> among <span className='dark:text-hovcol text-blue-800'>2500+</span> teams nationwide in <span className='dark:text-hovcol text-blue-800'>HackRx 3.0</span> Hackathon organized by <span className='dark:text-hovcol text-blue-800'>Bajaj Finserv Market</span></p>

              <p className='text-lg py-3 leading-8 max-w-1/2 mx-auto md:text-2xl'>Secured <span className='dark:text-hovcol text-blue-800'>top 10</span> in <span className='dark:text-hovcol text-blue-800'>HackNsut</span> Hackathon organised by <span className='dark:text-hovcol text-blue-800'>NSUT</span></p>
              <p className='text-lg py-3 leading-8 md:text-2xl max-w-1/2 mx-auto'>Solved <span className='dark:text-hovcol text-blue-800'>1000 +</span> problems on various coding platform</p>
              <p className='text-lg py-3 leading-8 md:text-2xl max-w-1/2 mx-auto'>Secured <span className='dark:text-hovcol text-blue-800'>67</span> global rank at Codechef Starter Contest</p>
              <p className='text-lg py-3 leading-8 md:text-2xl max-w-1/2 mx-auto'><span className='dark:text-hovcol text-blue-800'>1600+</span> rating at Leetcode</p>
              <p className='text-lg py-3 leading-8 md:text-2xl max-w-1/2 mx-auto'><span className='dark:text-hovcol text-blue-800'>3 star</span> at Codechef</p>

            </div>
          </div>
        </section>

        <section id='contact'>
          <div className='text-center text-gray-700 font-lobster py-10 dark:text-white '>
            <fieldset className="border-t border-slate-500 dark:border-hovcol">
              <legend className="mx-auto px-4 text-black text-2xl italic"> <h3 id='about' className=' text-4xl  md:text-6xl dark:text-blue-200 text-blue-800'>Contact Me</h3></legend>
            </fieldset>
            <div className='py-5'>
              <p className='text-lg py-3 leading-8 md:text-2xl max-w-lg mx-auto'>I am currently looking for new opportunities and I am interested in Software Development Role .Kindly Contact me through LinkedIn or Mail </p>
              <div className='flex gap-10 justify-center text-2xl md:text-3xl py-2'>
                <a href='https://www.linkedin.com/in/jharaghav/' target="_blank  " rel='noopener noreferrer'>

                  <GrLinkedinOption className=' hover:text-blue-800 dark:hover:text-hovcol hover:-translate-y-1' />
                </a>
                <a href='mailto:raghavkumarjha3209@gmail.com' target="_blank" rel='noopener noreferrer'>

                  <SiGmail className='hover:text-red-600 dark:hover:text-hovcol hover:-translate-y-1' />
                </a>
              </div>

            </div>
          </div>
        </section>

      </main>
    </div>

  )
}
